/**
 * Pure clone-planning logic — no database access, fully unit-testable.
 *
 * Given the metadata for the category-A (config) tables plus the full FK list of
 * the schema, produce an ordered ClonePlan that:
 *   1. clones tables parent-before-child (topological order),
 *   2. captures an old→new id map for every table whose id is referenced by
 *      another onboarded table,
 *   3. remaps surrogate-id foreign keys to the newly-generated ids,
 *   4. breaks FK cycles / self-references by deferring those remaps to a final
 *      UPDATE pass.
 *
 * Foreign keys to NATURAL keys (e.g. Config_Modules.ModuleName, TenantID) need
 * no remap — they resolve automatically once TenantID is swapped, because the
 * business key (ModuleName) is identical across tenants.
 */
import type { TableMeta, FkMeta, ClonePlan, CloneStep, RemapRef } from "./types.js";

export interface BuildPlanInput {
  /** tables to clone (category A) */
  cloneTables: string[];
  /** metadata for (at least) every clone table, keyed by bare table name */
  metas: Record<string, TableMeta>;
  /** every foreign key in the schema (used to detect who references whom) */
  allFks: FkMeta[];
  /** every table that participates in onboarding (A∪B∪C) — a clone table only
   *  needs an id map if one of THESE references its id. */
  onboardTables: Set<string>;
}

export function buildClonePlan(input: BuildPlanInput): ClonePlan {
  const { metas, allFks, onboardTables } = input;
  const cloneSet = new Set(input.cloneTables);

  const identityOf = (t: string): string | null =>
    metas[t]?.identityCol ?? null;

  // A non-identity, single-column GUID primary key (e.g. LandingPages.Id) cannot
  // be copied verbatim — it would collide with the template row's key. Such keys
  // are regenerated on clone with a fresh GUID. Natural text keys (Name/Code) are
  // intentionally NOT matched here — only uniqueidentifier columns or id/guid-named
  // string columns are treated as surrogate GUIDs.
  const regenInfo = (t: string): { col: string; expr: string } | null => {
    const meta = metas[t];
    if (!meta || meta.identityCol) return null; // identity is regenerated by the DB
    if (meta.pk.length !== 1) return null;
    const col = meta.pk[0];
    if (col.toLowerCase() === "tenantid") return null;
    const c = meta.columns.find((x) => x.name === col);
    if (!c) return null;
    const dt = c.dtype.toLowerCase();
    if (dt === "uniqueidentifier") return { col, expr: "NEWID()" };
    if (
      (dt === "nvarchar" || dt === "varchar" || dt === "nchar" || dt === "char") &&
      /(^id$|id$|guid)/i.test(col)
    )
      return { col, expr: "LOWER(CONVERT(nvarchar(36), NEWID()))" };
    return null;
  };

  // The key column captured into #map_<table> and remapped by children: the
  // identity column when present, otherwise a regenerated GUID PK.
  const keyColOf = (t: string): string | null =>
    metas[t]?.identityCol ?? regenInfo(t)?.col ?? null;

  // ── 1. Which clone tables are referenced BY surrogate id? ───────────────────
  // A table needs an old→new id map when some onboarded table has an FK whose
  // referenced column is that table's identity column.
  const idReferenced = new Set<string>();
  for (const fk of allFks) {
    if (!cloneSet.has(fk.refTable)) continue;
    if (!onboardTables.has(fk.child)) continue;
    const idCol = keyColOf(fk.refTable);
    if (idCol && fk.refCol === idCol) idReferenced.add(fk.refTable);
  }

  // ── 2. Surrogate-id FK edges between clone tables (child → parent) ──────────
  // We need TWO kinds of edge:
  //   • ORDERING edges — EVERY FK between clone tables (surrogate AND natural).
  //     A natural-key child (e.g. Config_ModuleLifeCycles → Config_Modules by
  //     ModuleName+TenantID) still requires its parent's NEW-tenant rows to
  //     exist first, so the parent must be cloned before the child even though
  //     no id translation is needed.
  //   • REMAP edges — only FKs whose referenced column is the parent's IDENTITY.
  //     These are the ones that need an old→new id translation.
  interface Edge { child: string; col: string; parent: string; }
  const edges: Edge[] = [];        // surrogate-id → need remap
  const orderEdges: Edge[] = [];   // all FKs → ordering only
  const seenEdge = new Set<string>();  // dedupe duplicate surrogate FK constraints
  const seenOrder = new Set<string>(); // dedupe ordering edges
  for (const fk of allFks) {
    if (!cloneSet.has(fk.child) || !cloneSet.has(fk.refTable)) continue;
    const oKey = `${fk.child}->${fk.refTable}`;
    if (!seenOrder.has(oKey)) {
      seenOrder.add(oKey);
      orderEdges.push({ child: fk.child, col: fk.col, parent: fk.refTable });
    }
    const parentId = keyColOf(fk.refTable);
    if (!parentId || fk.refCol !== parentId) continue; // natural-key → no remap
    const key = `${fk.child}|${fk.col}|${fk.refTable}`;
    if (seenEdge.has(key)) continue; // same column already mapped to this parent
    seenEdge.add(key);
    edges.push({ child: fk.child, col: fk.col, parent: fk.refTable });
  }

  // ── 3. Topological order (Kahn) over ALL FK edges, self-loops excluded ──────
  const adj = new Map<string, Set<string>>(); // parent → children
  const indeg = new Map<string, number>();
  for (const t of cloneSet) { adj.set(t, new Set()); indeg.set(t, 0); }
  for (const e of orderEdges) {
    if (e.child === e.parent) continue; // self-ref handled by deferred remap
    const kids = adj.get(e.parent)!;
    if (!kids.has(e.child)) { kids.add(e.child); indeg.set(e.child, indeg.get(e.child)! + 1); }
  }
  const ready = [...cloneSet].filter((t) => indeg.get(t) === 0).sort();
  const order: string[] = [];
  const left = new Map(indeg);
  while (ready.length) {
    const n = ready.shift()!;
    order.push(n);
    for (const m of [...adj.get(n)!].sort()) {
      left.set(m, left.get(m)! - 1);
      if (left.get(m) === 0) {
        // insert keeping deterministic sorted order
        const idx = ready.findIndex((x) => x > m);
        if (idx === -1) ready.push(m); else ready.splice(idx, 0, m);
      }
    }
  }
  // tables still with indegree > 0 are in cycles — append them deterministically
  const cycleTables = [...cloneSet].filter((t) => (left.get(t) ?? 0) > 0).sort();
  for (const t of cycleTables) if (!order.includes(t)) order.push(t);
  const position = new Map(order.map((t, i) => [t, i] as const));

  // ── 4. Per-table steps with inline vs deferred remap resolution ────────────
  // Group the surrogate-id FK edges by child for quick lookup.
  const edgesByChild = new Map<string, Edge[]>();
  for (const e of edges) {
    const arr = edgesByChild.get(e.child) ?? [];
    arr.push(e);
    edgesByChild.set(e.child, arr);
  }

  const steps: CloneStep[] = order.map((table) => {
    const meta = metas[table];
    if (!meta) throw new Error(`Missing metadata for clone table "${table}"`);
    const idCol = meta.identityCol;
    const regen = regenInfo(table);
    const keyCol = idCol ?? regen?.col ?? null;
    const tenantCol = meta.columns.find((c) => c.name.toLowerCase() === "tenantid")?.name ?? null;

    const insertColumns = meta.columns
      .filter((c) => !c.isComputed)
      .filter((c) => c.name !== idCol)
      .map((c) => c.name);

    const inlineRemap: RemapRef[] = [];
    const deferredRemap: RemapRef[] = [];
    for (const e of edgesByChild.get(table) ?? []) {
      // only remap columns we actually insert
      if (!insertColumns.includes(e.col)) continue;
      const ref: RemapRef = { col: e.col, parent: e.parent };
      const parentReady = e.parent !== table &&
        idReferenced.has(e.parent) &&
        position.get(e.parent)! < position.get(table)!;
      if (parentReady) inlineRemap.push(ref);
      else deferredRemap.push(ref); // self-ref, cycle, or forward ref
    }

    return {
      table,
      schema: meta.schema || "dbo",
      identityCol: idCol,
      pkRegen: regen,
      keyCol,
      idReferenced: idReferenced.has(table),
      insertColumns,
      tenantCol,
      inlineRemap,
      deferredRemap,
    };
  });

  return {
    steps,
    mapTables: order.filter((t) => idReferenced.has(t)),
    cycleTables,
  };
}
