/**
 * Table classification for RM ONE onboarding (core2 schema, per-tenant tables).
 * Generated from docs/onboarding_table_roles.csv — do not hand-edit; regenerate
 * with scripts/gen-clone-sql.ts source data if the classification changes.
 *
 *  A = CLONE_CONFIG   : configured-portal tables cloned from the template tenant
 *  B = EXCEL_ORG      : org structure supplied by the client's Excel
 *  C = EXCEL_TXN      : existing projects / CRM data supplied by the client's Excel
 *  SKIP_VENDOR_DEMO   : vendor (uGovernIT) demo-only tables — never onboarded
 *  SKIP_RUNTIME       : runtime/audit tables that fill themselves in use
 *
 * Template tenant = "LiRo POC" (LiRoDemo) — the web & mobile apps were built
 * against it, so its configuration matches what those apps expect.
 */
export const TEMPLATE_TENANT_NAME = "LiRoDemo";
export const TEMPLATE_TENANT_ID = "fcec991c-0b1c-4e41-8200-92c20ea3f536";

export const CLONE_CONFIG_TABLES: readonly string[] = [
  "ACRTypes",
  "ApplicationModules",
  "ApplicationRole",
  "ApplicationServers",
  "Applications",
  "CRMGeographies",
  "CRMRelationshipType",
  "CRMVerticals",
  "CheckListRoleTemplates",
  "CheckListRoles",
  "CheckListTaskTemplates",
  "CheckListTemplates",
  "Config_BudgetCategories",
  "Config_ClientAdminCategory",
  "Config_ClientAdminConfigurationLists",
  "Config_ConfigurationVariable",
  "Config_Dashboard_DashboardFactTables",
  "Config_Dashboard_DashboardPanelView",
  "Config_Dashboard_DashboardPanels",
  "Config_LeadCriteria",
  "Config_MailTokenColumnName",
  "Config_MasterAgreement",
  "Config_Master_RankingCriteria",
  "Config_MenuNavigation",
  // Config_ModuleLifeCycles + Config_Module_ModuleStages intentionally NOT cloned:
  // per product decision, new tenants must NOT inherit the golden tenant's full set
  // of default lifecycle templates (AIA / 10 Phase Non-AIA / Forecast Conversion /
  // Evaluation / Existing Conditions / Test). Instead the onboarding pipeline seeds
  // a single AIA standard lifecycle (see seedDefaultLifecycle in lib/pipeline.ts);
  // clients add more via "Manage lifecycles" (createLifecycleRds).
  "Config_ModuleMonitorOptions",
  "Config_ModuleMonitors",
  "Config_Module_DefaultValues",
  "Config_Module_EscalationRule",
  "Config_Module_FormLayout",
  "Config_Module_Impact",
  "Config_Module_ModuleColumns",
  "Config_Module_ModuleFormTab",
  // Config_Module_ModuleStages intentionally NOT cloned — see note above on
  // Config_ModuleLifeCycles. These are the per-lifecycle phase/stage rows.
  "Config_Module_ModuleUserTypes",
  "Config_Module_Priority",
  "Config_Module_RequestPriority",
  "Config_Module_RequestRoleWriteAccess",
  "Config_Module_RequestType",
  "Config_Module_SLARule",
  "Config_Module_Severity",
  "Config_Modules",
  "Config_PageConfiguration",
  "Config_ProjectClass",
  "Config_ProjectComplexity",
  "Config_ProjectInitiative",
  "Config_Service_ServiceCategories",
  "Config_Service_ServiceDefaultValues",
  "Config_Service_ServiceQuestions",
  "Config_Service_ServiceSections",
  "Config_Services",
  "Config_TabView",
  "Config_WikiLeftNavigation",
  "ContactExperienceTags",
  "DRQRapidTypes",
  "DRQSystemAreas",
  "EmployeeTypes",
  "ExperiencedTags",
  "FieldConfiguration",
  "FunctionRole",
  "FunctionRoleMapping",
  "FunctionalAreas",
  "GenericStatus",
  "GovernanceLinkCategory",
  "HelpCard",
  "HelpCardContent",
  "LandingPages",
  "LinkCategory",
  "LinkView",
  "ModuleStageConstraintTemplates",
  "ProjectAllocationTemplates",
  "ProjectSimilarityConfig",
  "ReportMenu",
  "SchedulerActions",
  "Studio",
  "TaskTemplates",
  "Templates",
  "TenantScheduler",
  "WikiArticles",
  "WikiContents",
];

export const EXCEL_ORG_TABLES: readonly string[] = [
  "AspNetRoles",
  "AspNetUserRoles",
  "AspNetUsers",
  "Company",
  "CompanyDivisions",
  "Department",
  "JobTitle",
  "JobTitleCostRateByDept",
  "Location",
  "ProjectDivisionRoles",
  "RoleBillingRateByDept",
  "Roles",
  "UserCertificates",
  "UserSkills",
];

export const EXCEL_TXN_TABLES: readonly string[] = [
  "BusinessStrategy",
  "CRMActivities",
  "CRMCompany",
  "CRMContact",
  "CRMProject",
  "CRMProjectAllocation",
  "CheckListTaskStatus",
  "CheckListTasks",
  "CheckLists",
  "ClientCountryFlags",
  "Country",
  "CriticalAmountMapping",
  "CurrentExchangeRates",
  "DMSDirectory",
  "DMSDocument",
  "Degrees",
  "Documents",
  "ExternalProjects",
  "FieldAliasCollections",
  "InitiativeProjectTypeMapping",
  "JobTitle_bak",
  "Lead",
  "LeadRanking",
  "LinkItems",
  "MessageBoard",
  "ModuleStageAliasMapping",
  "ModuleStageConstraints",
  "ModuleTasks",
  "ModuleUserStatistics",
  "Opportunity",
  "PMM",
  "POCMapping",
  "POR",
  "PORCompanyColumnMapping",
  "PORTypeMapping",
  "ProfileCertificates",
  "ProfileEducation",
  "ProfileExperienceTag",
  "ProfileLicenses",
  "ProfileSkills",
  "ProfileWorkExperience",
  "Profiles",
  "ProjectEstimatedAllocation",
  "ProjectStandardWorkItems",
  "RES",
  "Region",
  "RegionCountryStateMapping",
  "RelatedCompanies",
  "ResourceAllocation",
  "ResourceTimeSheet",
  "ResourceWorkItems",
  "Specialization",
  "Teams",
  "TicketHours",
  "TicketRelation",
  "Universities",
  "UserCertificatesMapping",
  "UserEducation",
  "UserHobbies",
  "UserLicenseMapping",
  "UserProjectExperience",
  "UserSkillMapping",
  "UserSpecializationMapping",
  "UserTeamMapping",
  "UserWorkExperience",
];

export const SKIP_VENDOR_DEMO_TABLES: readonly string[] = [
  "ACR",
  "Appointment",
  "AssetModels",
  "AssetVendors",
  "Assets",
  "BTS",
  "Contracts",
  "DRQ",
  "Environment",
  "GovernanceLinkItems",
  "INC",
  "ModuleBudget",
  "NPR",
  "NPRResources",
  "PMMEvents",
  "PRS",
  "RCA",
  "RequestTypeByLocation",
  "SVCRequests",
  "SurveyFeedback",
  "TSK",
  "TSR",
  "TenantRegistration",
  "VendorType",
];

export const SKIP_RUNTIME_TABLES: readonly string[] = [
  "ACR_Archive",
  "Assets_Archive",
  "BackgroundProcessStatus",
  "CRMCompany_Archive",
  "CRMContact_Archive",
  "CRMProject_Archive",
  "CRMServices_Archive",
  "Config_Module_TaskEmails",
  "DRQ_Archive",
  "DashboardSummary",
  "Emails",
  "INC_Archive",
  "Lead_Archive",
  "Log",
  "ModuleWorkflowHistory",
  "ModuleWorkflowHistory_Archive",
  "NPR_Archive",
  "Opportunity_Archive",
  "PMM_Archive",
  "ProjectStageHistory",
  "RCA_Archive",
  "ResourceAllocationMonthly",
  "ResourceUsageSummaryMonthWise",
  "ResourceUsageSummaryWeekWise",
  "ResourceUtilizationSummary",
  "ResourceUtilizationSummaryFooter",
  "State",
  "Summary_ResourceProjectComplexity",
  "TSR_Archive",
  "TicketEvents",
  "WorkflowSLASummary",
];

export const ONBOARD_TABLES: readonly string[] = [
  ...CLONE_CONFIG_TABLES,
  ...EXCEL_ORG_TABLES,
  ...EXCEL_TXN_TABLES,
];
