// A comprehensive catalogue of role names offered as suggestions when adding a
// new billing-rate role. The Billing Rates combobox lets a user pick any of
// these OR type a brand-new custom role — selecting one simply pre-fills the
// name (the role is created in core2 on save, deduped case-insensitively).
//
// The list is deliberately broad, spanning the full AEC (Architecture,
// Engineering & Construction) hierarchy plus general professional-services and
// support roles, so virtually any firm's role is one click away. It is only a
// convenience list; custom free-text entries are always allowed.

export const ROLE_CATALOG: string[] = [
  // ── Leadership / Executive ──
  "Chief Executive Officer (CEO)",
  "President",
  "Chief Operating Officer (COO)",
  "Chief Financial Officer (CFO)",
  "Chief Construction Officer (CCO)",
  "Managing Partner",
  "Senior Principal",
  "Principal",
  "Managing Principal",
  "Associate Principal",
  "Founding Principal",
  "Partner",
  "Vice President",
  "VP of Architecture",
  "VP of Engineering",
  "VP of Construction",
  "Director of Operations",
  "Director of Design",
  "Director of Business Development",
  "Director of Project Management",

  // ── Architecture ──
  "Principal Architect",
  "Senior Architect",
  "Project Architect",
  "Architect",
  "Intern Architect",
  "Architectural Designer",
  "Senior Designer",
  "Designer",
  "Junior Designer",
  "Job Captain",
  "Architectural Drafter",
  "Drafter",
  "Specifications Writer",
  "Interior Designer",
  "Senior Interior Designer",
  "Landscape Architect",
  "Urban Planner",
  "BIM Manager",
  "BIM Specialist",

  // ── Engineering (all disciplines) ──
  "Principal Engineer",
  "Senior Engineer",
  "Project Engineer",
  "Engineer",
  "Junior Engineer",
  "Engineer-in-Training (EIT)",
  "Civil Engineer",
  "Senior Civil Engineer",
  "Structural Engineer",
  "Senior Structural Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Plumbing Engineer",
  "MEP Engineer",
  "Geotechnical Engineer",
  "Environmental Engineer",
  "Fire Protection Engineer",
  "Transportation Engineer",
  "Water Resources Engineer",
  "Drainage Engineer",
  "Utilities Engineer",
  "Land Development Engineer",
  "Engineering Designer",
  "Engineering Drafter",
  "CAD Technician",
  "CAD Manager",

  // ── Project Management / Controls ──
  "Program Manager",
  "Project Director",
  "Senior Project Manager",
  "Project Manager",
  "Assistant Project Manager",
  "Project Controls Manager",
  "Project Coordinator",
  "Project Administrator",
  "Planner",
  "Scheduler",
  "Document Controller",
  "Commissioning Manager",

  // ── Construction / Field ──
  "Construction Manager",
  "General Superintendent",
  "Senior Superintendent",
  "Superintendent",
  "Assistant Superintendent",
  "Field Engineer",
  "Site Engineer",
  "Foreman",
  "Safety Manager",
  "Safety Officer",
  "Quality Manager",
  "QA/QC Manager",
  "Estimator",
  "Senior Estimator",
  "Chief Estimator",
  "Cost Engineer",
  "Quantity Surveyor",
  "Procurement Manager",
  "Contracts Manager",
  "Subcontractor",
  "Skilled Tradesperson",
  "Laborer",

  // ── Survey / GIS / Visualization ──
  "Land Surveyor",
  "Surveyor",
  "GIS Specialist",
  "Visualization Specialist",
  "Rendering Artist",

  // ── Consulting / Professional Services ──
  "Managing Director",
  "Senior Manager",
  "Engagement Manager",
  "Senior Consultant",
  "Consultant",
  "Senior Associate",
  "Associate",
  "Senior Analyst",
  "Analyst",
  "Subject Matter Expert",
  "Intern",

  // ── Administration / Finance / Support ──
  "Office Manager",
  "Executive Assistant",
  "Administrative Assistant",
  "Controller",
  "Finance Manager",
  "Accountant",
  "Bookkeeper",
  "Billing Specialist",
  "Payroll Specialist",
  "HR Manager",
  "Human Resources",
  "Marketing Manager",
  "Marketing Coordinator",
  "Business Development Manager",
  "IT Manager",
  "IT Support",
  "Receptionist",
];
